export const COUNTRY_CODES = [
  { code: '55', label: 'Brasil', flag: '🇧🇷' },
  { code: '1', label: 'EUA / Canada', flag: '🇺🇸' },
  { code: '351', label: 'Portugal', flag: '🇵🇹' },
  { code: '54', label: 'Argentina', flag: '🇦🇷' },
  { code: '56', label: 'Chile', flag: '🇨🇱' },
  { code: '57', label: 'Colombia', flag: '🇨🇴' },
  { code: '52', label: 'Mexico', flag: '🇲🇽' },
  { code: '598', label: 'Uruguai', flag: '🇺🇾' },
  { code: '595', label: 'Paraguai', flag: '🇵🇾' },
  { code: '591', label: 'Bolivia', flag: '🇧🇴' },
  { code: '51', label: 'Peru', flag: '🇵🇪' },
  { code: '593', label: 'Equador', flag: '🇪🇨' },
  { code: '58', label: 'Venezuela', flag: '🇻🇪' },
  { code: '34', label: 'Espanha', flag: '🇪🇸' },
  { code: '33', label: 'Franca', flag: '🇫🇷' },
  { code: '49', label: 'Alemanha', flag: '🇩🇪' },
  { code: '39', label: 'Italia', flag: '🇮🇹' },
  { code: '44', label: 'Reino Unido', flag: '🇬🇧' },
  { code: '81', label: 'Japao', flag: '🇯🇵' },
  { code: '86', label: 'China', flag: '🇨🇳' },
  { code: '91', label: 'India', flag: '🇮🇳' },
  { code: '61', label: 'Australia', flag: '🇦🇺' },
  { code: '27', label: 'Africa do Sul', flag: '🇿🇦' },
  { code: '234', label: 'Nigeria', flag: '🇳🇬' },
  { code: '971', label: 'Emirados Arabes', flag: '🇦🇪' },
  { code: '966', label: 'Arabia Saudita', flag: '🇸🇦' },
  { code: '972', label: 'Israel', flag: '🇮🇱' },
  { code: '7', label: 'Russia', flag: '🇷🇺' },
  { code: '82', label: 'Coreia do Sul', flag: '🇰🇷' },
  { code: '90', label: 'Turquia', flag: '🇹🇷' },
]
